# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_trainee_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Test_trainee(object):
    def setupUi(self, Test_trainee):
        Test_trainee.setObjectName("Test_trainee")
        Test_trainee.resize(532, 344)
        self.centralwidget = QtWidgets.QWidget(Test_trainee)
        self.centralwidget.setObjectName("centralwidget")
        self.findButton = QtWidgets.QPushButton(self.centralwidget)
        self.findButton.setGeometry(QtCore.QRect(430, 269, 92, 22))
        self.findButton.setObjectName("findButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 270, 411, 20))
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 21, 511, 221))
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 300, 411, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.deleteButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton_2.setGeometry(QtCore.QRect(430, 299, 92, 22))
        self.deleteButton_2.setObjectName("deleteButton_2")
        Test_trainee.setCentralWidget(self.centralwidget)

        self.retranslateUi(Test_trainee)
        QtCore.QMetaObject.connectSlotsByName(Test_trainee)

    def retranslateUi(self, Test_trainee):
        _translate = QtCore.QCoreApplication.translate
        Test_trainee.setWindowTitle(_translate("Test_trainee", "TestTrainee"))
        self.findButton.setText(_translate("Test_trainee", "Finde"))
        self.lineEdit.setText(_translate("Test_trainee", "Input text"))
        self.lineEdit_2.setText(_translate("Test_trainee", "Input ID"))
        self.deleteButton_2.setText(_translate("Test_trainee", "Delete"))
